# Generated by Django 5.2.17 on 2026-10-05 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParametreJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_day_int",
                    models.PositiveSmallIntegerField(
                        default=20,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(28),
                        ],
                        verbose_name="jour de lancement du job",
                    ),
                ),
            ],
            options={
                "verbose_name": "paramètre job",
                "verbose_name_plural": "paramètre job",
            },
        ),
        migrations.CreateModel(
            name="SoldeOM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(verbose_name="date/heure du solde")),
                ("balance", models.BigIntegerField(verbose_name="solde disponible")),
                ("insert_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "solde OM",
                "verbose_name_plural": "soldes OM",
                "ordering": ["-datetime", "-id"],
            },
        ),
    ]
