# Generated by Django 5.2.17 on 2026-10-05 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trx_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="ID transaction",
                    ),
                ),
                (
                    "insert_type",
                    models.CharField(
                        choices=[("manuel", "Manuel"), ("auto", "Automatique (SMS)")],
                        default="manuel",
                        max_length=10,
                    ),
                ),
                (
                    "debit_credit",
                    models.SmallIntegerField(
                        choices=[(-1, "Dépense"), (1, "Alimentation")]
                    ),
                ),
                ("montant", models.PositiveBigIntegerField()),
                (
                    "sms",
                    models.TextField(
                        blank=True, null=True, verbose_name="SMS d'origine"
                    ),
                ),
                ("insert_date", models.DateTimeField(auto_now_add=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="budgets.allocationbudget",
                    ),
                ),
            ],
            options={
                "ordering": ["-insert_date", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("debit_credit__in", [-1, 1])),
                        name="transaction_debit_credit_valide",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("montant__gt", 0)),
                        name="transaction_montant_positif",
                    ),
                ],
            },
        ),
    ]
