# Generated by Django 5.2.17 on 2026-10-05 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TypeBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(editable=False, max_length=20, unique=True)),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                ("insert_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "type de budget",
                "verbose_name_plural": "types de budget",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "montant_budget",
                    models.PositiveBigIntegerField(
                        verbose_name="montant alloué par mois"
                    ),
                ),
                (
                    "montant_max",
                    models.PositiveBigIntegerField(verbose_name="plafond du budget"),
                ),
                (
                    "montant_min",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="solde minimal après allocation"
                    ),
                ),
                (
                    "solde_alert",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="seuil d'alerte"
                    ),
                ),
                (
                    "autogen_fin_mois",
                    models.BooleanField(
                        default=False,
                        verbose_name="allocation automatique en fin de mois",
                    ),
                ),
                ("insert_date", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budgets",
                        to="budgets.typebudget",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AllocationBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField(verbose_name="début")),
                ("date_to", models.DateField(verbose_name="fin")),
                (
                    "montant_alloue",
                    models.PositiveBigIntegerField(verbose_name="montant alloué"),
                ),
                ("insert_date", models.DateTimeField(auto_now_add=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="budgets.budget",
                    ),
                ),
            ],
            options={
                "verbose_name": "allocation de budget",
                "verbose_name_plural": "allocations de budget",
                "ordering": ["-date_from", "budget__name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("date_to__gte", models.F("date_from"))),
                        name="allocation_dates_coherentes",
                    ),
                    models.UniqueConstraint(
                        fields=("budget", "date_from"),
                        name="allocation_unique_par_periode",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.CheckConstraint(
                condition=models.Q(("montant_min__lte", models.F("montant_max"))),
                name="budget_min_lte_max",
            ),
        ),
    ]
